### ISSUE TITLE
Custom TI mode

### ISSUE THREAD

**Issue by yatli** [jmamma/MIDICtrl20_MegaCommand#101]
- [x] Trig key handler
- [x] Custom LEDs

**Comment by jmamma** [comment]
How far along are you?

I am going to write up the Sysex handler now.

ie:

class TrigInterface : public MidiSysexListenerClass

**Comment by yatli** [comment]
MCL side? Still trying to bring up the dev env (single threaded mind).
Can help testing the code tonight.

**Comment by jmamma** [comment]
All good, just dont want to double up on work. i'm 70% of the way there.

**Comment by yatli** [comment]
Tracking: #102

**Comment by yatli** [comment]
Related: #73

**Comment by jmamma** [comment]
Need to re-think global settings now. 

Should we allow the user to specify base channel, or just stick with the default channels used by MCL.

--

Also, because we no are no longer monitoring note messages for TI, MIDI machines will be compatible with MCL.

**Comment by yatli** [comment]
> Should we allow the user to specify base channel, or just stick with the default channels used by MCL.

What's the implication?

**Comment by yatli** [comment]
Closing now. Implemented.
