### ISSUE TITLE
Reverb and kit name

### ISSUE THREAD

**Issue by onoma2** [jmamma/MIDICtrl20_MegaCommand#106]
Hello guys,

Thank you for the job you do. 
I’ve stumbled upon two issues recently.
1) sometimes reverb send goes 127 on slot1/track1. I can’t find out why
2) also first 2-3 kits in MD look empty-named (without names and without dashes) when I pair the units 

MCL 2.60
MD 1.70

**Comment by jmamma** [comment]
Thanks for this.

We're able to replicate (2) and are working on a fix.

Need more information on (1). In what situation ?

**Comment by jmamma** [comment]
(2) is fixed in MD OS 1.71 and MCL 2.61
