### ISSUE TITLE
2.61

### ISSUE THREAD

**Issue by jmamma** [jmamma/MIDICtrl20_MegaCommand#109]
Almost ready to go.

Updated documentation + Changelog. 

ARP page needs support for the HD44780 .

Any chance you can do this @yatli ?

**Comment by yatli** [comment]
A little bit busy with the day job at the moment..

**Comment by jmamma** [comment]
Music Producer by night. Diligent employee by day. No time for firmware dev.

**Comment by jmamma** [comment]
done 26cfac06ed893aca597b619931e6385e21f0a874

**Comment by jmamma** [comment]
https://github.com/jmamma/MIDICtrl20_MegaCommand/releases/tag/2.61

**Comment by yatli** [comment]
😂 thanks!
