### ISSUE TITLE
Wavetable synthesis

### ISSUE THREAD

**Issue by yatli** [jmamma/MIDICtrl20_MegaCommand#119]
We can prepare morphing waveforms (like the Ableton Live new synth) and pack them into one sample.

Load them up in a linear ROM machine, and control it to move in different directions...
Even if we only have a linear axis to control the offset, we can use different traverse algorithms to walk between different waves:

Linear morph loop:

![image](https://user-images.githubusercontent.com/20684720/84597774-c1542280-ae98-11ea-9e68-9c01825638ba.png)

Morph tree:

![image](https://user-images.githubusercontent.com/20684720/84597811-e6e12c00-ae98-11ea-85a2-18fef2f35343.png)

etc.

**Comment by jmamma** [comment]
I've been thinking bout how to do this for a while.

I think you also need a 'static' region for each waveform 1 2 3, where the waveform is not morphing.

**Comment by yatli** [comment]
Given that each wave itself needs an interval in the axis, yeah, the static region. But if the static regions are long we may not have enough resolution to do the morph smoothly.

What's your take on this? I remember you have knowledge about creating few cycle samples. What's the shortest possible waveform length?

**Comment by jmamma** [comment]
Shortest possible length == waveform length of fundamental frequency.
