### ISSUE TITLE
To be fixed.

### ISSUE THREAD

**Issue by jmamma** [jmamma/MIDICtrl20_MegaCommand#122]
- [x] Display "POLY LINK" when changing parameters of linked poly tracked.
- [x] Shift and reverse is not shifting/reversing slide mask.
- [ ] Allow folder manipulation in load project page.

**Comment by yatli** [comment]
> Allow folder manipulation in load project page

folder manipulation?

**Comment by jmamma** [comment]
cd
mkdir
etc.

**Comment by albadort76** [comment]
Minor bug : in chromatic mode if the kit is changed in the MD, it's not following in the MC. Need to go out of the chromatic menu and then come back in for effective change.
MD 1.71, MC 2.70
Megacommand is fantastic :)

**Comment by jmamma** [comment]
> Minor bug : in chromatic mode if the kit is changed in the MD, it's not following in the MC. Need to go out of the chromatic menu and then come back in for effective change.

Yeah, this is a known 'feature/issue'. We need to implement some changes on the MD side to alert the MC when the kit's machines are changed. 

> MD 1.71, MC 2.70
> Megacommand is fantastic :)

cheers. let us know if you run into anything else.
