### ISSUE TITLE
Asset files in SD card?

### ISSUE THREAD

**Issue by yatli** [jmamma/MIDICtrl20_MegaCommand#132]
Icons, debug messages etc.
Need a preprocessor for this to work.
The fw installation will be two-stage, a installer and the main FW.

**Comment by jmamma** [comment]
Yeah i was thinking of this...

**Comment by jmamma** [comment]
Yeah i was thinking of this...

**Comment by jmamma** [comment]
Yeah i was thinking of this...

**Comment by jmamma** [comment]
Cons:
Loading time would potentially increase.. 
Firmware installation would be more complicated

**Comment by yatli** [comment]
Also see this: https://github.com/majekw/optiboot/blob/supermaster/optiboot/examples/flash_program/flash_program.ino

Reprograms the flash without a host computer. This could allow us to dynamically load programs, without writing an emulator.
