### ISSUE TITLE
active peer fails if MD sequencer running v 3.0

### ISSUE THREAD

**Issue by jmamma** [jmamma/MIDICtrl20_MegaCommand#136]
@yatli can you take a look.

**Comment by yatli** [comment]
No repro:

- MD and A4 connected to MC
- MC powered off
- MD + A4 power on
- MD start sequencer
- MC power on
- MC active peering OK for MD
- A4 press key
- MC active peering OK for A4
- A4 power off
- MC active peering OK for A4 disconnect
- A4 power on, start A4 sequencer, press key
- MC active peering OK for A4

**Comment by jmamma** [comment]
No worries.

I haven't seen this issue for the last few days.
