### ISSUE TITLE
New SDFat version

### ISSUE THREAD

**Issue by jmamma** [jmamma/MIDICtrl20_MegaCommand#137]
https://github.com/greiman/SdFat

@yatli ^

**Comment by yatli** [comment]
So.. we can use it to reduce FW size?

**Comment by jmamma** [comment]
yes, should be smaller. not sure how much.

**Comment by jmamma** [comment]
i also discovered that there is a bug with arduino mega bootloader which caused the last 8KB of ROM space to be unusable.

**Comment by yatli** [comment]
I followed the url you provided -- it looks like it's a FUSE setting that protects the region?

**Comment by jmamma** [comment]
yes possibly.

**Comment by yatli** [comment]
https://github.com/Optiboot/optiboot is an alternative bootloader with reduced size (512 bytes only), and hopefully, does not inherit the bugs from the official bootloader.

Any mods done to the bootloader will require an ISP programmer, though.

**Comment by yatli** [comment]
Oh wait...
This can be done with a loader program, self-programming the chip:

https://github.com/Optiboot/optiboot/wiki/InstallingOnChips#installing-using-a-specialized-bootloader-loader-sketch

**Comment by jmamma** [comment]
I think you still need to go through ISP

**Comment by yatli** [comment]
ow naw..
