### ISSUE TITLE
When MC is connected, FUNCTION+EXTENDED should restore MCL seq sounds?

### ISSUE THREAD

**Issue by yatli** [jmamma/MIDICtrl20_MegaCommand#139]
Currently, FN+EXTENDED will reset MD to a kit in the MD memory.

-- or, save the current kit into MD memory during chain load?

**Comment by jmamma** [comment]
function + extend loads up the undo kit. I forgot exactly how this works, but we never populate the undo kit with data, only the workspace kit. I suppose when we send, we should populate both.

**Comment by jmamma** [comment]
Saving the MD Kit doesn't play nice with parameter locks, hence why I was so eager to get workspace working.

**Comment by jmamma** [comment]
implemented.
