### ISSUE TITLE
Assortment of recent bugs

### ISSUE THREAD

**Issue by yatli** [jmamma/MIDICtrl20_MegaCommand#154]
- [x] Chain mode isn't effective
- [x] LEV of all tracks stuck at 127 on chain write
- [x] Chain write do not reliably activate all selected tracks
- [x] Chain write on a tight time budget result in off-beat tracks. The problem goes away if I stop/restart playback.
- [x] Save results in wrong kit name
- In X.04 with trig chain of >=3 tracks, sometimes one of the tracks is double-triggered (b-boom)

**Comment by yatli** [comment]
```
C:\Users\Yatao\Documents\Arduino\hardware\MIDICtrl20_MegaCommand\avr\cores\megacommand\MD\MDMessages.cpp:214:57: warning: left shift count >= width of type [-Wshift-count-overflow]
 uint8_t MDMachine::get_model() { return model &= ~(1 << 17); }
```

**Comment by jmamma** [comment]
```C:\Users\Yatao\Documents\Arduino\hardware\MIDICtrl20_MegaCommand\avr\cores\megacommand\MD\MDMessages.cpp:214:57: warning: left shift count >= width of type [-Wshift-count-overflow]
 uint8_t MDMachine::get_model() { return model &= ~(1 << 17); }
```

Bit 17 is set as tonality. So we must clear it when returning model type ??

**Comment by jmamma** [comment]
```Chain write on a tight time budget result in off-beat tracks. The problem goes away if I stop/restart playback.```

Yeah this one is on the list.

**Comment by jmamma** [comment]
```LEV of all tracks stuck at 127 on chain write```

This is expected behaviour. CONFIG -> MACHINEDRUM -> NORMALIZE.
(LEV is boosted to 127, and VOL is lowered to compensate.)

**Comment by jmamma** [comment]
void m_putc(uint8_t *msg, uint16_cnt) { ... }
ALWAYS_INLINE() void sendRaw(const uint8_t *msg, uint16_t cnt) { m_putc(msg, cnt); }

Is this conversion bad practice? I've got an issue with this function not working.

**Comment by yatli** [comment]
>  uint8_t MDMachine::get_model() { return model &= ~(1 << 17); }
> 
> Bit 17 is set as tonality. So we must clear it when returning model type ??

uint8_t return type will automatically clear that

nvm, this should be fine.

**Comment by yatli** [comment]
> This is expected behaviour. CONFIG -> MACHINEDRUM -> NORMALIZE.

I see. I think I hear the difference because I have an LFO on VOL -- should turn normalization off.

**Comment by jmamma** [comment]
uint8_t return type will automatically clear that

good point.

**Comment by jmamma** [comment]
I see. I think I hear the difference because I have an LFO on VOL -- should turn normalization off.

The is normalisation code should scale LFOs accordingly, but i think the relationship is not linear so there may be some differences. 

```
11 void MDMachine::scale_vol(float scale) {
 12   DEBUG_PRINT_FN();
 13   params[MODEL_VOL] = (uint8_t)((float)params[MODEL_VOL] * scale);
 14   if (params[MODEL_VOL] > 127) {
 15     params[MODEL_VOL] = 127;
 16   }
 17   if ((lfo.destinationParam == MODEL_VOL) && (lfo.destinationTrack == track)) {
 18     params[MODEL_LFOD] = (uint8_t)((float)params[MODEL_LFOD] * scale);
 19 
 20     if (params[MODEL_LFOD] > 127) {
 21       params[MODEL_LFOD] = 127;
 22     }
 23     lfo.depth = params[MODEL_LFOD];
 24   }
 25 }
 26 
 27 float MDMachine::normalize_level() {
 28   DEBUG_PRINT_FN();
 29   if (level == 127) {
 30     return 1.0;
 31   }
 32 
 33   float scale = (float)level / (float)127;
 34   level = 127;
 35 
 36   scale_vol(scale);
 37   return scale;
 38 }
```

**Comment by jmamma** [comment]
Seems like the timing issue only occurs when MIDI tracks on grid 2 are loaded.

**Comment by jmamma** [comment]
3ad60ec

Timing feels good now. Can you confirm @yatli

**Comment by jmamma** [comment]
```
Save results in wrong kit name
In X.04 with trig chain of >=3 tracks, sometimes one of the tracks is double-triggered (b-boom)
```

I can't replicate these.

I also cant replicate your merge bug with GND-X machines.

**Comment by yatli** [comment]
I can't repro the trig chain problem now.

**Comment by yatli** [comment]
Another bug -- chaining while playing result in wrong automation -- I have a track without slides, but chaining to it result in a knob being modulated from 0 to 127 and back again rapidly.

**Comment by jmamma** [comment]
LFOTrack ?

**Comment by yatli** [comment]
oh didn't thought of that.
But when I stop/start it's gone

**Comment by jmamma** [comment]
Can you replicate the chain movement that got you in to the state?

**Comment by jmamma** [comment]
@yatli 
```
/Applications/Arduino_nightly.app/Contents/Java/hardware/MIDICtrl20_MegaCommand/avr/cores/megacommand/CommonTools/RingBuffer.h:111:16: error: invalid conversion from 'volatile void*' to 'void*' [-fpermissive]
     memcpy(buf + wr, src, s * sizeof(C));
            ~~~~^~~~
```
?

**Comment by yatli** [comment]
Add `-fpermissive` to g++ flags

**Comment by yatli** [comment]
FYI current arduino platform.txt options:

```
compiler.cpp.flags=-std=gnu++1z -c -Os {compiler.warning_flags} -MMD -Wno-attributes -Wno-write-strings -fpermissive -fno-exceptions -fno-threadsafe-statics -fno-rtti -ffunction-sections -fdata-sections -flto=jobserver -Wl,--gc-section,--defsym=__stack=0x8021ff,--section-start,.data=0x802100,--defsym=__heap_end=0x80ffff,--relax -I{build.core.path}/Midi -I{build.core.path}/GUI -I{build.core.path}/CommonTools -I{build.core.path}/Elektron -I{build.core.path}/MD -I{build.core.path}/MidiTools -I{build.core.path}/Sequencer -I{build.core.path}/MNM -I{build.core.path}/PageTools -I{build.core.path}/MDSketches -I{build.core.path}/MDPages -I{build.core.path}/A4 -I{build.core.path}/SPI -I{build.core.path}/Wire -I{build.core.path}/Adafruit-GFX-Library -I{build.core.path}/Adafruit_SSD1305_Library -I{build.core.path}/SdFat -I{build.core.path}/SDCard -I{build.core.path}/MCL
```

**Comment by jmamma** [comment]
nice

**Comment by yatli** [comment]
Converted the X tunnel song to MCL -- timing is good. Also tight chain writes are robust! 🎖

**Comment by yatli** [comment]
Trying to extract that project for you via MegaCom:

![image](https://user-images.githubusercontent.com/20684720/110064556-46c18f00-7da8-11eb-8f55-ec913c6993f7.png)

**Comment by yatli** [comment]
MegaCom behavior is interesting -- matches the design goals -- more bandwidth on simpler pages (17KB/s on MIXER), and "nicer" on fancy pages (7KB/s on GRID)

Screensaver = 30KB/s

**Comment by yatli** [comment]
[X_mcl.zip](https://github.com/jmamma/MIDICtrl20_MegaCommand/files/6088062/X_mcl.zip)

**Comment by yatli** [comment]
hmm I still cannot activate chain mode

**Comment by jmamma** [comment]
Haven't even had a chance to look at megacom yet. you'll need to recreate the binaries because last time I tried they didnt work.

I'll be heading off for a few hours.  back later tonight.

**Comment by jmamma** [comment]
Haven't even had a chance to look at megacom yet. you'll need to recreate the binaries because last time I tried they didnt work.

I'll be heading off for a few hours.  back later tonight.

**Comment by jmamma** [comment]
> hmm I still cannot activate chain mode

what do you mean?

**Comment by yatli** [comment]
Set row 0 to chain to row 1, manual
Chain write row 0, expecting it to jump to row 1 after playback
Not jumping, not displaying the estimated jump time below current time

**Comment by jmamma** [comment]
there used to be a chain bug on row 0. maybe it came back.

**Comment by yatli** [comment]
Tried row 1 no banana

**Comment by jmamma** [comment]
Did you set chain mode to AUTO

**Comment by jmamma** [comment]
Loops need to be greater than 0 per slot

**Comment by jmamma** [comment]
@yatli can you double check and report back.

**Comment by jmamma** [comment]
⏳

**Comment by yatli** [comment]
Woke up

**Comment by jmamma** [comment]
Wake up Samurai, we've got a firmware to burn.

**Comment by yatli** [comment]
Just tested -- chain update on any row, loop=1, row=next, cannot activate.
Side effect is, kit name is lost after the update

**Comment by jmamma** [comment]
Chain mode ?

**Comment by yatli** [comment]
Yes, the button 3 menu, use encoder3 to select all tracks, set row to next, set loop to 1, release button 3 -- kit name is now blank.

**Comment by jmamma** [comment]
No i mean... from grid page.. hold shift 2. Set CHAIN mode from MANUAL to AUTO

**Comment by yatli** [comment]
It works!
AUTO never worked for me before -- I was sticking with MANUAL all along

**Comment by jmamma** [comment]
haha 😆

**Comment by jmamma** [comment]
I think MCL 3.10 is done. I've updated the changelog.

**Comment by jmamma** [comment]
That means it's time.

**Comment by yatli** [comment]
![image](https://user-images.githubusercontent.com/20684720/110103376-d8e58980-7de0-11eb-8f2d-745dc87e4223.png)

**Comment by yatli** [comment]
Yahoooo

**Comment by jmamma** [comment]
preparing binaries...

**Comment by jmamma** [comment]
Ready to go here. I sent you a message elsewhere on github for your verification .

**Comment by jmamma** [comment]
okay tested here.

🚀

**Comment by jmamma** [comment]
Going live...

**Comment by jmamma** [comment]
https://github.com/jmamma/MIDICtrl20_MegaCommand/releases/tag/3.10
