### ISSUE TITLE
Deprecate Param/Locks page?

### ISSUE THREAD

**Issue by jmamma** [jmamma/MIDICtrl20_MegaCommand#160]
Do we need this anymore?

Does it afford us any advantages?

**Comment by yatli** [comment]
- UI for cond trig
- UI for lock assignment (unique)

**Comment by yatli** [comment]
~~But I guess that's all there's left.~~

**Comment by yatli** [comment]
Also, is there possibility that we will support non-MD device on GridA?

**Comment by jmamma** [comment]
> * UI for cond trig
> * UI for lock assignment (unique)

can already edit the various step masks from the StepEdit page. Or did you mean something else?

**Comment by jmamma** [comment]
> Also, is there possibility that we will support non-MD device on GridA?

It's technically possible. The implementation is flexible. What did you have in mind ?

**Comment by yatli** [comment]
The more I play with MC+MnM, the more I want P-Lock instead of event drawing.

**Comment by jmamma** [comment]
make up your mind 😀

**Comment by yatli** [comment]
My current setup:

![image](https://user-images.githubusercontent.com/20684720/113853758-9e508180-97d0-11eb-9451-a7d3ba8a99fe.png)

Sweet spot for me.

**Comment by jmamma** [comment]
wheres the MNM ?

**Comment by jmamma** [comment]
![1509984452_858270](https://user-images.githubusercontent.com/8424097/113857216-95b67600-97e5-11eb-9937-693174b77bfe.jpg)

This has been my setup for the past 3 weeks.  I miss making music 😭

**Comment by yatli** [comment]
oww.

**Comment by yatli** [comment]
> wheres the MNM ?

MnM/A4 cannot stand that they cannot be P-Locked so they paired up and ran away to the side desk.

**Comment by yatli** [comment]
OT: why me in box??

**Comment by jmamma** [comment]
🗑️

**Comment by yatli** [comment]
> 🗑️

OT: me box, me box

**Comment by jmamma** [comment]
deprecated
