### ISSUE TITLE
Saving Kit while in Step Edit

### ISSUE THREAD

**Issue by ninqe** [jmamma/MIDICtrl20_MegaCommand#163]
Hey there,
Just found that while trying to safe a kit while I am in 'Step Edit' the [func] + [<] and [>] combination does work as it should and shifts the corresponding steps in the track, however when I try to (re)name the Kit I am not able to toggle the cursor left and right as this function is already taken by step-shifting. Up and Down works as usual. Same goes for 'Lock Page'.
Only minor bug, workaround is easy by switching to another page in MCL. Maybe an 'if'-condition could be implmented for when in 'Kit-menu' on MD

**Comment by jmamma** [comment]
Thanks. Good catch.

**Comment by jmamma** [comment]
Fixed in next release.
