### ISSUE TITLE
Wrong pitch information shown for steps without PTC lock

### ISSUE THREAD

**Issue by unekinn** [jmamma/MIDICtrl20_MegaCommand#165]
Steps to reproduce
----
1. Use a tonal sound, set pitch to 0 on the Machinedrum
2. In an empty pattern, enter "Step edit" on MCL
3. Place two trigs
4. Parameter lock `PTC` on the first trig to `C0`
5. Press play and hear two different pitches for the two trigs
6. Hold the second trig, but don't parameter lock anything. Notice that the `PTC` still says `C0`, even though the second trig's pitch hasn't changed
7. Place a third trig. Notice that `PTC` still says `C0` on the MCL, even if the sounding pitch is not `C0`.
8. Parameter lock the second trig to e.g. `E0`
9. Hold the third trig, but don't parameter lock. `PTC` now erroneously says `E0`
10. Hold the first trig, `PTC` correctly says `C0`
11. Hold the third trig, `PTC` now erroneously says `E0`

This seems to happen whether or not you've placed locks on other parameters than `PTC`.

(Maybe related: When placing a new trig, the `PTC` from the previously locked step will show up and stay on screen even after releasing the trig. You can turn the encoder to change the `PTC` value, but nothing will actually change.)

Actual result
----
If there's no `PTC` lock for a trig, it will show the pitch info for the previously "held" trig with an actual `PTC` lock.

Expected result
----
Trigs without at `PTC` lock should show `--`, or possibly the note value corresponding to the non-locked pitch for the sound on the Machinedrum.

Placing a new trig should not cause `PTC` to stay on-screen and be editable (with no actual result) after releasing the trig

**Comment by jmamma** [comment]
Thanks will chase this down.
