### ISSUE TITLE
Issue with resistor arrays / matrices, a way to bypass ?

### ISSUE THREAD

**Issue by defalutz** [jmamma/MIDICtrl20_MegaCommand#171]
Hi,

i´ve had a an issue that almost caused my mind to melt; in the end i decided that the problem was a faulty board and i gave up, de-soldered what i could and reused it on a new board.

The error that i could find gave the result a black screen and no indication of a working MCL in any way.

The error source i found to be R1 and R2, the resistor arrays / matrices. They should only "join" or short each other (you know what i mean, the multimeter should only beep) at the squared pads. Problem is, there are other shorts where the two connect and these are why the MCL don´t work. 

![IMG_20210908_142021](https://user-images.githubusercontent.com/79913028/132538259-4861217e-7b27-409d-8473-ae2cb6015fbe.jpg)

For example, one pair often seems to be joined more than other pairs and that´s the third from above here on the attached picture.

![res-arrays_joined](https://user-images.githubusercontent.com/79913028/132537345-89ff03af-a53a-43a5-909e-f9f01b7a0052.jpg)

Now, when i first had this bug i thought i checked all the remaining PCB´s for errors like this but obviously not. Now i have seven partly built units with this bug. A few with just this pair shown, other with some other pair, or multiple pairs.

I would be very happy if i could in some way avoid or bypass the shorted / joined pads in some way. 

Can you see a solution? Is there a way to bypass the bug? I´ll try anything but i don´t know how the resistor arrays work so i don´t know how to work around this.

**Comment by jmamma** [comment]
Sounds like a faulty pcb. You could try and etch away the copper where you think the short is, but it's a messy job. 
Better to abandon the board, as it may cause you other problems down the line.

**Comment by defalutz** [comment]
Yeah, that was my thought too. But since there were many with this issue, i will give etching away a try at least One time.
Is it enough to cut away the copper between the two pads that are joined? They are side by side so should be easy. Otherwise i will have to order more PCBs, this time i Will use pcbway instead probably..

**Comment by defalutz** [comment]
Noticed a incredibly weird behaviour.
The PCB´s i checked and deemed OK suddenly has the error i described above, which kind of sucks because it´s 9 that i almost have finished.
Even more strange is that the ones that had the error and that i stopped building on, suddenly dont have the bug - not even one of them (7)!
I don´t know how to interpret this!
Also, i had four that was finished and decided to do a random check on one of them - and yes, it did have the bug on the exact same place as above.
I´ve measured and re-measured but cant make heads or tails of it. A faulty multimeter? It was quite cheap but have served me well so far.. Changed batteries but that did nothing.

I think i will start with finish building the ones that only have the error on one place and hope for the best, before i go tearing them apart. If they are ok, most of them in any case, i will check and try with the next with two bugs, aand last with three.
If it pans out i might try to use the ones that earlier i discarded, at least one, and see if it works.

Weird, right? Any thoughts?

**Comment by frnktrpz** [comment]
Are you perhaps testing the MC's on a (somewhat/partially) conductive surface? Wristwatch shorting something out while you're making measurements? Working in front of a wall of unshielded speakers? PCB's sitting in direct sunlight for hours on end? House built on top of an ancient Viking burial ground?  
If you have such a significant quantity of these boards, especially if they're already in various build states, and you have ruled out any factors in your environment and process then it might be worth seeing if you can get one of the pcb's (assuming they're all from the same batch) x-rayed and check it for some sort of production error.

**Comment by defalutz** [comment]
I´m testing them on an anti-static surface, but i suppose anything can be possible.
Everyone is from the same batch, but i don´t have the know-how or money to make it worth getting them x-rayed, because i suppose it´s not cheap?
The bad ones are all in the same batch; i made 50 and the first 25 were without errors, while in the second package of 25 things started misbehavin´

Anyway, since they now behave very irratically i will try to finish the few than have least problems, since it´s so little left to do on them. The ones than have only a few things left i will run all the build checks on, and then try to finish them and see if they start up properl even if the meter indicates trouble.

Thaks for your input! I will get back with status update on this weird issue.

**Comment by frnktrpz** [comment]
Aren't most anti-static surfaces made to be highly conductive?
