### ISSUE TITLE
Feature Requests MCL 2021/12/27

### ISSUE THREAD

**Issue by ninqe** [jmamma/MIDICtrl20_MegaCommand#172]
- [ ] 1. Trig Condition(s) and Arrow- up/down
So far all conditions have to be set with Arrow-up starting by L-n going to P-n and so on. Using Arrow Up for L-n's and Arrow Down for P-n's would correspond with other elektron devices behaviour as in CCW for P and CW for L.

- [ ] 2. Fill and Not-Fill as Conditions and Performance Tool
Implementation of a Fill feature as in a classic 808 manner. Adding the Conditions FILL and NOT-FILL and having the [song/pattern] Knob on MD UI as momentary switch for these conditions.

- [ ] 3. Soundmanager MD UI Implementation
Sound Manager Page on MC to be controlled by arrow/Yes/No knobs of MD UI

- [ ] 4. Reimplementation of Global Swing and/or Swing Per Track
Reimplementation of Swing as a performance tool; having a percentage per track rather than microtiming per step

- [ ] 5. Euclidean Sequence Generator 
A Euclidean Sequence Generator maybe as a page or Edit Mode on MC, micabeza brought that up somewhere

- [ ] 6. MC Encoders on Mixer Page
"utilise the dormant 4 encoders as an external CTR-4P, or as a micro CTR-ALL for all filters and all LFOs depth and speed, would be really useful/expressive.  how about holding down a button to capture the pots movement over a patterns duration." Waftlord

- [ ] 7. Enhanced Performance/Scene mode
"Enhanced Performance/Scene mode feature idea/request in MCL menu: 16 programmable parameter scenes across 16 trigs, saved to each row. hold scene trig and turn pot can assign (a finite amount of) tracks parameters to each scene. switching scenes has embedded slide for adjusted params. MCL 4 encoders become assignable to any chosen parameters (a mini external CTR-4)
Or one knob macros like rytm perf knob. YES/NO buttons could be assigned too, SHIFT ALL L/R, global pitch shift +- etc" Waftlord

- [ ] 8. MD mode to receive midi Ch. Inp for each track on its respective Channel
"Let me turn this into a feature request then: Can we get a mode or setting that allows each MD channel to receive their own midi channel input? Much like the Nord 3p." https://www.elektronauts.com/t/megacommand-mcl-4-0/159098/215

- [ ] 9. EXT. control of Grid via midi notes
"map editor or some sort grid mode to trigger clips(or tracks) using external midi notes (which would open to the possibility to map it to an external grid controller" https://www.elektronauts.com/t/megacommand-mcl-4-0/159098/66

**Comment by RogerLevy** [comment]
I'd like to request Retrig support, or an Arpeggiator track which could serve the same purpose assuming the Rate can be fast enough to do rolls (as fast as 128th notes?)
