### ISSUE TITLE
Saving individual Output settings 

### ISSUE THREAD

**Issue by ALAKTU** [jmamma/MIDICtrl20_MegaCommand#178]
Hi,
First of all amazing Job ! 

Is it possible to save the “global” routing settings of the MD (individual output routing)
For each pattern.
If i load a pattern it all gets set back to main,
Even after saving on the MCL with changed routing in Global.

tried to search for this in the forums but missed it and or couldn’t find it.

❤️

**Comment by jmamma** [comment]
Yes, set the routing via MCL's Route Page.

There is a special slot in Gridy Y labelled "RT". When this slot is saved, the routing information from the route page is stored. Similarly if you load this slot it will load the Routing information.
 
If you perform Group Load or Group Save with the FX group enabled, the RT slot is automatically included.

**Comment by ALAKTU** [comment]
Thank u very much!!
❤️
