### ISSUE TITLE
Updating bootloader via ISCP programmer

### ISSUE THREAD

**Issue by cokosha** [jmamma/MIDICtrl20_MegaCommand#180]
After uploading bootloader 1.04 I can't upload firmwares via USB XLoader. 
Uploading firmware via ISCP USBasp is OK.

**Comment by jmamma** [comment]
The new USB firmware defaults to USB-MIDI.

A SYSEX string can be sent via MIDI to switch to serial for OS upload.

Alternatively, the new version of MCL has a boot menu with "OS UPGRADE" that will put the USB chip in to serial mode.

So the instructions require you to upgrade MCL first, then the USB microcontroller.

Jump on the discord if you still need help.
