### ISSUE TITLE
How to invert rotation direction of encoders?

### ISSUE THREAD

**Issue by ctag-fh-kiel** [jmamma/MIDICtrl20_MegaCommand#188]
How to invert rotation direction of encoders?

**Comment by ctag-fh-kiel** [comment]
Changed line 92 of Encoders.cpp to 
return -inc; // simply negate inc for inversion of rotation direction for encoders.

Works for me :)

**Comment by jmamma** [comment]
nice work, what are you hacking together 🙃 ?

**Comment by ctag-fh-kiel** [comment]
Just the hardware controller, the encoders I have generate inverted pulses, had to fix that. 
One could possibly move this to the boot menu, where one could soft configure encoder rotation?

**Comment by ctag-fh-kiel** [comment]
I have published a .hex firmware file of 4.51 with inverted rotation direction here:
https://github.com/ctag-fh-kiel/MCL/releases/tag/4.51-inverted-encoder-rotation
