### ISSUE TITLE
Give a warning when a kit/a pattern is about to be cleared?

### ISSUE THREAD

**Issue by yatli** [jmamma/MIDICtrl20_MegaCommand#29]
I've been through this a few times..
Trying to compose something in the internal sequencer -> accidentally cleared it with a chain write -> no pattern, no kit, no nothing :(

**Comment by jmamma** [comment]
undo feature perhaps?

The save mode definitely needs it. i've accidently used save page instead of write a few times.

**Comment by yatli** [comment]
Now with the snp dumps I'm infinitely more confident :)

**Comment by jmamma** [comment]
We also have copy/paste buffer now. 

I think the additional latency required to copy RAM to a recovery buffer before write, 
is not feasible. Particularly in chain mode when timing is already tight.
