### ISSUE TITLE
Alternative chassis design RFC

### ISSUE THREAD

**Issue by yatli** [jmamma/MIDICtrl20_MegaCommand#34]
I'm working on a metal chassis design

![Render](https://user-images.githubusercontent.com/20684720/62836809-b7bac680-bc99-11e9-993c-d28cd3138aba.JPG)

Basically, I'd like to make it low-cost, durable and mountable. The current design consists of two parts, each can be produced with sheetmetal (304, 6061 etc.)

Potential problems:

1. The screw tap hole "ears" are less than optimal. May consider bend the whole edge instead of cutting those 6 ears.
2. Screen height?
3. No power switch hole...

**Comment by yatli** [comment]
Back:

![image](https://user-images.githubusercontent.com/20684720/62836856-43ccee00-bc9a-11e9-8df5-f0ba03b3d9fc.png)

**Comment by yatli** [comment]
Close-in of one of the ears (which might be a problem, cuts finger, etc.):

![image](https://user-images.githubusercontent.com/20684720/62836872-81ca1200-bc9a-11e9-89f3-b268a1292c6b.png)

**Comment by yatli** [comment]
Some by-product that might be useful:

![image](https://user-images.githubusercontent.com/20684720/62837051-5694f200-bc9d-11e9-88ce-319876a7002b.png)

**Comment by jmamma** [comment]
Woah. Cool. That 3D model is excellent.

The base of the screen pcb should be approximately 6mm above the height of the mainboard pcb (ignoring any components).

The above sentence is valid if you plan on using the the MEC switches + switchcaps.

**Comment by yatli** [comment]
Adjusting the design -- should be 1mm taller 😅
Could I upload the board 3D model to this repo?

**Comment by jmamma** [comment]
Forgot to say. https://github.com/jmamma/MegaCommand_Design is the hardware repo.

Any hardware related designs should be uploaded there.

**Comment by yatli** [comment]
Wilco!
