### ISSUE TITLE
Transmit sysex dumps from/to sdcard.

### ISSUE THREAD

**Issue by yatli** [jmamma/MIDICtrl20_MegaCommand#36]
- [x] Pattern dumps
- [x] Sample dumps (MIDI SDS)
- [x] Interfacing with sample name query facility
- ~~Automated macros for entering dump receive mode~~

**Comment by yatli** [comment]
tracking: #35

**Comment by jmamma** [comment]
Regarding Sample Dumps.

The idea was to have a Sample Manager page, with basic WAV editing features. A lot of that code is already implemented in the WavDesigner.

Also, to receive samples from the MD you need to use the undocumented SYSEX (macro) commands to navigate the menus and transmit sample from the SampleManager menu.

**Comment by jmamma** [comment]
Rather than storing all snapshot data in a single .snp binary. I'm wondering if it would be better to organise snapshots via directories. Each directory would be a single snapshot and hold 128 patterns 64 kits + 8 globals as individual files.

Then the Snapshot page can be a generalised MD Sysex dump page.  You could choose to restore an entire directory, or just single files.

**Comment by yatli** [comment]
The .snp binary is a direct representation of MC data structures and could be more convenient than serializing/deserializing syx files.

That said, having the flexibility of choosing individual elements is very useful. Luckily because the data structures are fixed-size, we can simply seek and access.

I'm thinking of this as, separating .snp and .syx as two features -- .syx involves additional parsing, checking the header (pattern dumps have different header than SDS dumps), entering the MD sysex menu etc, while .snp page simply stop playback and "hack" the content in/out.

**Comment by yatli** [comment]
@jmamma time to do sample manager?
I've got command 0x33 for querying sample names.
We can use the name as a hash index that can be back-referenced to an exact WAV file in SD card.

**Comment by yatli** [comment]
Tracking: #104
