### ISSUE TITLE
FileBrowser Improvements

### ISSUE THREAD

**Issue by jmamma** [jmamma/MIDICtrl20_MegaCommand#37]
The original idea was to have a file browser class that could be easily extended for use amongst different pages. Having a common base class would save on program size and memory requirements.

The difficulty here is that the FileBrowser often requires additional GUI functionality depending on its context.
For example the SoundBrowser page and LoadProject page both require reading the SD card file system. But have different functional requirements.

The current FileBrowser class allows additional GUI elements to be activated, through the use of boolean flags. The ability to traverse parent directories, to Save or Create new files are accessible by appending faux menu items before the list of files of the cwd.

There might be a better way to do this. Dynamic menu items? Function callbacks?

**Comment by jmamma** [comment]
Rather than appending GUI elements to the file system list. Could use the first half of the screen to display an options menu, when Shift2  is pressed. This could then display page functions like [ "Save", "New", "Delete", "Rename"] etc.

**Comment by yatli** [comment]
> when Shift2 is pressed

... or use encoder 3/4?
like, encoder 1/2 --> right pane file navigation
encoder 3/4 --> left pane menu items

**Comment by yatli** [comment]
I tried the SHIFT idea on the TextInputPage.
It a bit harder to wrap around the head but the result is positive.
The key is to hide the low level details in the base class, and declare multi-modal methods for FileBrowserPage (normal vs. menu, just like normal vs. char-pane), then the derived class supply custom drawing/event handling routines for the SHIFT layer.

**Comment by jmamma** [comment]
I

> > when Shift2 is pressed
> 
> ... or use encoder 3/4?
> like, encoder 1/2 --> right pane file navigation
> encoder 3/4 --> left pane menu items

I wanted to get users to predict that shift2 may access a hidden sub menu on most pages.
For example, the slot menu is accessible from the GridPage by pressing shift 2.

**Comment by yatli** [comment]
I like the consistency with GridPage.

**Comment by yatli** [comment]
Implemented, closing.
