### ISSUE TITLE
NewProjectPage should use the TextInputPage for project name manipulation

### ISSUE THREAD

**Issue by jmamma** [jmamma/MIDICtrl20_MegaCommand#39]

**Comment by yatli** [comment]
I can do a SHIFT-encoder text input menu for better input experiences :)

**Comment by jmamma** [comment]
You mean similar to Elektron. Char select window?

Could be better overall.

**Comment by yatli** [comment]
yep, but without 4-way arrow keys, we'd better make a single-row interface (sliding left/right, which gives preview of neighbor chars)

**Comment by jmamma** [comment]
2+ rows would make for faster navigation. 
If you're going to open up a new page for Char Select, might as well use up all of the screen space :-).

Only downside I see is that it wont be compatible with HD44780 display. Though I think it might be time to drop support for that display.

**Comment by yatli** [comment]
I'll see if I can do it in an hour or two. ;)

**Comment by yatli** [comment]
ok it's done, see #35

**Comment by jmamma** [comment]
Cool. Had a quick read through. 

I will upload tonight and test it out :rocket:

**Comment by yatli** [comment]
#35 now addresses this issue.

**Comment by yatli** [comment]
Closing this issue now.
