### ISSUE TITLE
FX Pages.

### ISSUE THREAD

**Issue by jmamma** [jmamma/MIDICtrl20_MegaCommand#40]
Pages for controller Delay + Reverb.

Also need an intuitive +musical way of loading delay + reverb + compressor + eq settings from the current row/slot

**Comment by yatli** [comment]
Add a column (track) for FX?
Pretty much like what A4 does.

**Comment by jmamma** [comment]
Perhaps.

I also contemplated allowing columns > 16 to host special track types.
One of which could be of FX type.
Another type could be MIDI allowing tempo changes and such.

The problem is, how do you load these tracks from the MD trigger interface when you're limited to 16 buttons.

A proposed solution would be to have a layered GRID.
We could put each device on its own layer.

**Comment by yatli** [comment]
Primary feature complete. Moving reminding work to backlog.
