### ISSUE TITLE
Improve GUI and Button Mapping.

### ISSUE THREAD

**Issue by jmamma** [jmamma/MIDICtrl20_MegaCommand#42]
Visually the step sequencer should be drawn using drawrect commands (similar to mixer and cue pages)

Functionally we may be able to improve on encoder+ button layout.

**Comment by yatli** [comment]
A few things I'd been wanting, also items extracted from #22 :

- Smooth editing workflow
  - ~~Switch tracks from MC (Encoder 4 is unassigned currently)~~
  - A clearer connection/differentiation between the grid and the internal sequencer. Currently the "workspace" is a bit implicit. Perhaps a dot at the corner of the grid elements, if they are the source of the sequencer? We can keep thinking about this.
  - Or, directly editing the grid elements? (mentioned in #22)
  - Consistent navigation

- A more compact and informative UI layout
  - Labels/hints about the button functionalities
  - Icons/hints for parameters

**Comment by jmamma** [comment]
I think I already implemented track switching? 
Shift2 + MD Trig.

---

In any case. In addition to visual improvements. The GUI button mapping needs work. 

There are currently at least 4 configurations of button mappings which can be categorised as followed:

1. - Save/Write Pages 
2. - SequencerPages.
3. - Auxillary/PageSelect Pages
4. - FileBrowser + Menu Pages

An example of inconsistency across the above groups:

- Auxillary pages are exited by pressing encoder buttons.
- FileBrowser + Menu Pages are exited by pressing function buttons. Encoder buttons are used for forward action.
- Sequencer Pages are exited by pressing their corresponding entry button, which is an encoder button.

**Comment by yatli** [comment]
> I think I already implemented track switching?

Looks like I'm lagging behind again :)

**Comment by yatli** [comment]
> There are currently at least 4 configurations of button mappings

Also `TextInputPage`, Encoders == confirm, Button{1,3,4} == Exit

> FileBrowser + Menu Pages are exited by pressing function buttons. Encoder buttons are used for forward action.

This has been a great UX for me. Also consistent with the text input page. I've somehow trained myself to recognize Button1 as "Back".

> Auxillary pages are exited by pressing encoder buttons.
> Sequencer Pages are exited by pressing their corresponding entry button, which is an encoder button.

A bit confusing for me -- there's no clear connection which sequencer page is associated to which encoder button. Some times I just recognize encoder1 as exit, in case it didn't work (switched from another), push again.

**Comment by jmamma** [comment]
> Auxillary pages are exited by pressing encoder buttons.
Sequencer Pages are exited by pressing their corresponding entry button, which is an encoder button.

> A bit confusing for me -- there's no clear connection which sequencer page is associated to which encoder button. Some times I just recognize encoder1 as exit, in case it didn't work (switched from another), push again.

The only solution here is to put all the sequencer pages in to the quick select page.
Or get more buttons 😛

**Comment by yatli** [comment]
Visual help example (maybe too heavy):

![image](https://user-images.githubusercontent.com/20684720/66898595-11d66000-f02c-11e9-8491-7cb6546a5321.png)

**Comment by yatli** [comment]
Alternative:

![image](https://user-images.githubusercontent.com/20684720/66899183-1ea78380-f02d-11e9-96bb-0361c552344b.png)

**Comment by yatli** [comment]
A more lightweight "visual cue" approach:

![image](https://user-images.githubusercontent.com/20684720/66899936-6d095200-f02e-11e9-8336-4416d3e768b7.png)

**Comment by yatli** [comment]
"white" version:

![image](https://user-images.githubusercontent.com/20684720/66900109-be194600-f02e-11e9-8ac3-26952f2b92c0.png)

**Comment by jmamma** [comment]
I do like the Alternative design.

The lightweight version is more ergonomic but what information is it communicating to the user?

**Comment by jmamma** [comment]
These modes can be enabled/disabled from system menu.

**Comment by yatli** [comment]
The lightweight cues only tell user that the system will respond when pressing the hinted buttons.

**Comment by jmamma** [comment]
@yatli when you have a chance.

Can you create a confirmation window using your Alert Popup.

 "Some input text?"
🛑 YES or NO

Returns true or false.

**Comment by yatli** [comment]
Done. See #35, https://github.com/jmamma/MIDICtrl20_MegaCommand/pull/35/commits/52fef1a0fd1911f8c6f0e63be6217e6f1c15e8e7

Usage:

```c++
  if (mcl_gui.wait_for_confirm("Confirm", "Save snapshot?"))
  {
    gfx.alert("Confirmed", "Save");
  }

```

**Comment by jmamma** [comment]
We should change the default MCL font to the MD char_select_font. Also visible in the KIT menu.

Need to start drawing some glyphs.

**Comment by jmamma** [comment]
> We should change the default MCL font to the MD char_select_font. Also visible in the KIT menu.
> 
> Need to start drawing some glyphs.

Hmm,  I tried creating two variants of this font. After all that I think I prefer the adafruit font.

**Comment by yatli** [comment]
The story behind tomthumb font: https://robey.lag.net/2010/01/23/tiny-monospace-font.html

Good old time.

**Comment by jmamma** [comment]
The elektron 'small' font pre-dates tom thumb by 10+ years. I made some minor modification to tomthumb to match.

**Comment by yatli** [comment]
Implemented. Closing now.
