### ISSUE TITLE
Tempo instability, especially during chain write

### ISSUE THREAD

**Issue by yatli** [jmamma/MIDICtrl20_MegaCommand#45]
After a few writes (chained looping), some tracks start to drop out.

I've recorded a video:
https://yadli.net/index.php/s/4eWm6nNypANqmgt

**Comment by jmamma** [comment]
DEBUG_MODE 

There are still DEBUG_PRINT lines in the interrupt/sequencer code.
Kills performance.
Need to clean it up.

**Comment by yatli** [comment]
Ahhh, you're right!
