### ISSUE TITLE
Chromatic mode: copy machine to poly voice tracks?

### ISSUE THREAD

**Issue by yatli** [jmamma/MIDICtrl20_MegaCommand#55]

**Comment by jmamma** [comment]
I had the option to implement this, but decided against it for some reason.

Thinking about it again now:

I think the justification was that chain-mode should determine track type.

Also, which poly track is the master track to be copied ?

**Comment by jmamma** [comment]
Chromatic page needs a rework anyway. 

MCLGUI:draw_encoder()

MCLGUI:draw_keyboard( ) {
//Draw piano keyboard
//Highlight notes when played.
}

etc.

**Comment by jmamma** [comment]
Also maybe POLY_CONFIG should not be a global setting, ~but a per row setting.~

Or rather, each slot should be flagged as either poly or mono. If poly then update POLY_CONFIG on chain load/write.
