### ISSUE TITLE
Rework sequencer pages.

### ISSUE THREAD

**Issue by jmamma** [jmamma/MIDICtrl20_MegaCommand#56]
Popup menu for micro timing? conditional trigs?

Draw step sequencer.

MCLGUI::draw_trigger(width, button_state, led_state) {

drawLed()
drawRect() 
etc
  .     .    .
[  ]  [  ]  [  ]

}

**Comment by yatli** [comment]
Added design files in #47, request for comments :)

![Sequencer](https://user-images.githubusercontent.com/20684720/67360043-7b5bee80-f597-11e9-9c9f-52a86c2e5441.png)

![Sequencer](https://user-images.githubusercontent.com/20684720/67360055-81ea6600-f597-11e9-90cb-6447dfbbcc8f.gif)

**Comment by yatli** [comment]
merged 🚀🚀🚀
