### ISSUE TITLE
MidiClock

### ISSUE THREAD

**Issue by jmamma** [jmamma/MIDICtrl20_MegaCommand#61]
I thought MidiClock on port 2 was not working correctly. But I think it may be the Analog4 no longer transmitting reliable clock.

MD clock signal looks tight when plugged in to either port 1 or port 2.

**Comment by jmamma** [comment]
Confirmed. MD sees same jitter from A4.

A4 clock used to be tight. need to try the latest OS to see if that fixes.

**Comment by yatli** [comment]
Could calibration fix that?

**Comment by jmamma** [comment]
Closing this for now.
