### ISSUE TITLE
Standardise Page GUI.

### ISSUE THREAD

**Issue by jmamma** [jmamma/MIDICtrl20_MegaCommand#63]
- [x] FXPages

- [x] RAMPages

- [x] Route Page
- [x] SavePage

- [x] WritePage

**Comment by jmamma** [comment]
SeqPage::display()

Some of the code here such as printing labels should be made in to member function(s) and take string pointer as arg.

**Comment by yatli** [comment]
About Save / Write page:

I'd like a graphical representation of the data flow, for example:

```
SAVE
              SEQ.png \
                      >----- GRID.png
              MD.png /
```

**Comment by yatli** [comment]
> Some of the code here such as printing labels should be made in to member function(s) and take string pointer as arg.

You mean the info1 and info2 lines?

**Comment by jmamma** [comment]
Yeah. Also, I think we might need some type of MCLGUIPage class parent of SeqPage.
So the draw_knob functions and other standard GUI elements can be shared to other page types.

**Comment by jmamma** [comment]
> About Save / Write page:
> 
> I'd like a graphical representation of the data flow, for example:
> 
> ```
> SAVE
>               SEQ.png \
>                       >----- GRID.png
>               MD.png /
> ```

Are you talking about graphical representation of Pages + button combinations? 

--- 

 I think you mean data flow between MC and MD during transfer ?

**Comment by yatli** [comment]
> Are you talking about graphical representation of Pages + button combinations?

Actually I mean, "data is going from the SEQ to the GRID, and optionally, merging from MD"

**Comment by yatli** [comment]
I just uploaded the latest HEAD with LFO pages.
Excellent work!

**Comment by jmamma** [comment]
> I just uploaded the latest HEAD with LFO pages.
> Excellent work!

Pretty much got every feature I wanted in to the LFOPage. And the LFOs work better than I expected.

**Comment by jmamma** [comment]
Also, have you seen the Trimetric Sprites:

https://github.com/jmamma/MIDICtrl20_MegaCommand/tree/dev/art/sprites/trimetric

I think they will look quite good when rendered on the OLED.

**Comment by yatli** [comment]
Yes, and hence the "MD.png" thing :)

**Comment by yatli** [comment]
> Some of the code here such as printing labels should be made in to member function(s) and take string pointer as arg.

Done.

**Comment by jmamma** [comment]
> > Some of the code here such as printing labels should be made in to member function(s) and take string pointer as arg.
> 
> Done.

Nice work.
