### ISSUE TITLE
SDDrivePage

### ISSUE THREAD

**Issue by jmamma** [jmamma/MIDICtrl20_MegaCommand#68]
- [x] 1.  Should verify if MD.connected = true before starting save.
- [x] 2. Should verify return of getBlocking() and fail if false.
- [x] 3. Should display Confirmation Popup on Load so that MD contents isn't accidentally overwritten.

**Comment by jmamma** [comment]
@yatli can you sort this out when you have time ?

We have to finish and release the firmeare before Behringer catches on and decides to clone the MC.

**Comment by yatli** [comment]
Behringer, seriously..

**Comment by yatli** [comment]
- [x] Should confirm if saving to existing file.
