### ISSUE TITLE
Out-of-box experience is broken

### ISSUE THREAD

**Issue by yatli** [jmamma/MIDICtrl20_MegaCommand#72]
Completed the second MC!
Boot it up, greeted with a nice splash page animation, peering, and...
A black stripe is drawn in the center of the screen, and it freezes.
It's actually in the new page dialog but it didn't display correctly.
Move the cursor around and the page will show itself.

**Comment by jmamma** [comment]
I haven't tested on a "clean" SD card yet for this version.

Old behaviour is to detect if there is a mcl_config file. If not, then create new project.
Changes to the NewProject page may have broken this.

**Comment by jmamma** [comment]
Resolved with:

c2d2d0c3d90efd6f8b61a90747418ee39ce9b5a8

and

42ea618a11cd4e587e379286090edbac9ffcbf36
