### ISSUE TITLE
LoudnessPage intermittent.

### ISSUE THREAD

**Issue by jmamma** [jmamma/MIDICtrl20_MegaCommand#78]
Loudness adjustments have no effect sometimes ?

**Comment by jmamma** [comment]
Only works when sequencer is stopped.

**Comment by jmamma** [comment]
MDKit transfer is throttled, use MD.sendMachine instead.

**Comment by yatli** [comment]
Also it's not refreshing correctly. No clearDisplay()?

**Comment by jmamma** [comment]
I've fixed that in latest patches.

**Comment by jmamma** [comment]
page_select() pr

**Comment by jmamma** [comment]
333a7ac2b3014f81b5454dfcd193a8a10826078e

**Comment by yatli** [comment]
Cool, closing.
