### ISSUE TITLE
Feature Freeze and 2.50 Release.

### ISSUE THREAD

**Issue by jmamma** [jmamma/MIDICtrl20_MegaCommand#79]
Close last PR.
More testing.

Release date Dec 1st.

**Comment by jmamma** [comment]
@yatli does this sound good to you?

**Comment by yatli** [comment]
Oh yeah.
I'm setting up a tracker for the blocking issues: https://github.com/jmamma/MIDICtrl20_MegaCommand/milestone/1

**Comment by jmamma** [comment]
Thanks. I've just updated the Changelog. Take a look to see if I missed anything.

**Comment by yatli** [comment]
Changelog not checked in?

**Comment by jmamma** [comment]
I've pushed back the release to the 7/12/2019.

**Comment by yatli** [comment]
No rush.

**Comment by jmamma** [comment]
The HD44780 code is actually very close.

Surprised how well we've managed to preserve functionality across the two displays.

**Comment by jmamma** [comment]
@yatli 

I'm more or less satisfied with the state of the MCL 2.50

I've exhausted all the bugs I can find 🤞 

If you would like to do more testing of your own. Before release?

**Comment by jmamma** [comment]
Documentation is done.

**Comment by yatli** [comment]
Thanks! That's a lot of fixes!

I'm currently wired into the hack project. Please feel free to proceed on the release :)

**Comment by yatli** [comment]
I'm wondering peoples' reaction on seeing Him.

:)

**Comment by jmamma** [comment]
Just compiled final binaries.

Will test tonight, then tag and release.

**Comment by jmamma** [comment]
Need to test these as well

Windows:
https://github.com/xinabox/xLoader
Mac:
http://paulkaplan.me/HexUploader/

**Comment by yatli** [comment]
I can test the Win32 part.

**Comment by jmamma** [comment]
[binary candidates.zip](https://github.com/jmamma/MIDICtrl20_MegaCommand/files/3971636/binary.candidates.zip)

**Comment by yatli** [comment]
I'm trying to figure out how to successfully load the FW with xloader...

**Comment by jmamma** [comment]
Maybe it doesnt work with the 2560. I just tried out the mac tool and you have specifically select the board type.

**Comment by jmamma** [comment]
[binaries candidate 2.zip](https://github.com/jmamma/MIDICtrl20_MegaCommand/files/3972771/binaries.candidate.2.zip)

fixed an lfo bug ^

**Comment by yatli** [comment]
let me hack together a working xloader.

**Comment by jmamma** [comment]
can you try https://sourceforge.net/projects/bitburner/

**Comment by yatli** [comment]
what's the command you use usually to upload?

**Comment by jmamma** [comment]
${AVR_DIR}/bin/avrdude -C${AVR_DIR}/etc/avrdude.conf -v -V -patmega2560 -cwiring -P${DEV} -b115200 -D -Uflash:w:./main.hex

**Comment by yatli** [comment]
the stock XLoader is missing the correct arguments for avrdude.
we'll have to edit avrdude.conf and devices.txt

**Comment by jmamma** [comment]
ah

**Comment by jmamma** [comment]
i'm having a git meltdown. cant auto merge dev in to master. conflicts

**Comment by jmamma** [comment]
"git merge -X theirs dev" didn't know this trick.

**Comment by jmamma** [comment]
```Justins-MacBook-Pro-3:megacommand jmammarella$ md5 main.hex
MD5 (main.hex) = 248c6b45e21d565c167a326238343299
Justins-MacBook-Pro-3:megacommand jmammarella$ md5 ~/Desktop/mcl_binaries/mcl_2_5_0_oled.hex 
MD5 (/Users/jmammarella/Desktop/mcl_binaries/mcl_2_5_0_oled.hex) = 248c6b45e21d565c167a326238343299
```
merge was good.

**Comment by yatli** [comment]
~~you can `git diff dev` to check the merged result~~
edit: just realized you've got the exact binary build :)

**Comment by yatli** [comment]
working command:
```
.\avrdude.exe -p atmega2560 -c wiring -D -P \\.\COM4 -b 115200 -U flash:w:"C:\Tools\XLoader V1.339\mcl_2_5_0_oled.hex":i
```

trying to hack it into the xloader config file

**Comment by jmamma** [comment]
Can you set the avrdude.exe path to be the default location installed by arduino ide.

**Comment by jmamma** [comment]
https://github.com/jmamma/MIDICtrl20_MegaCommand/releases/tag/untagged-decad224e317dcb19584

^ release draft

**Comment by yatli** [comment]
- update avrdude.exe
- update libusb0.dll
- the format for devices.txt goes like: `name;cpu;programmer;baudrate`
- it's missing a `-D` flag
- simple code injection: `megacommand;atmega2560;wiring -D;115200;`
- bingo!

![image](https://user-images.githubusercontent.com/20684720/70990134-d9bccd80-20ff-11ea-9232-e24c7ffa4914.png)

**Comment by jmamma** [comment]
h4x0r ^

**Comment by yatli** [comment]
Assembled uploader:

[XLoader.zip](https://github.com/jmamma/MIDICtrl20_MegaCommand/files/3972900/XLoader.zip)

**Comment by jmamma** [comment]
"update avrdude.exe
update libusb0.dll"
^ what does this mean?

**Comment by jmamma** [comment]
ah avrdude.exe was part of the archive. naughty.

**Comment by jmamma** [comment]
where should we host it?

**Comment by yatli** [comment]
well, here?

**Comment by jmamma** [comment]
license ?

**Comment by yatli** [comment]
because I've modified the devices config section -- the only device option is "megacommand"

**Comment by yatli** [comment]
The license of XLoader:

```
Copyright (c) 2012, Geir Lunde
All rights reserved.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL <COPYRIGHT HOLDER> BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
```

**Comment by jmamma** [comment]
i need a lawyer.

**Comment by jmamma** [comment]
i have windows 10 now. i will test.

**Comment by yatli** [comment]
In my layman's understanding this is just a no-warranty clause

**Comment by jmamma** [comment]
awesome. just tested. works great!

**Comment by yatli** [comment]
awesome. big time!

**Comment by jmamma** [comment]
We did it.

https://github.com/jmamma/MIDICtrl20_MegaCommand/releases/tag/2.50

**Comment by jmamma** [comment]
If you're happy, i'll post it over to elektronauts

**Comment by yatli** [comment]
sure!

**Comment by jmamma** [comment]
Thanks for accompanying me on this journey Yateo. 

I had dreams of this firmware when I was performing live in 2010. I wrote the first minicommand sketch in 2012. It's taken 7 years to get this far. If only I could send a megacommand back in time.

😄

**Comment by yatli** [comment]
I feel warm. :)

And time flies. 15 years ago when I started programming, I work on a miniature 6502 PDA with 160x80 LCD.

I did not know that after all these years, I'll be still enjoying 8 bit programming, with even smaller screens!

**Comment by jmamma** [comment]
It's a shame JMamma & Yatli Enterprises doesn't have any money. 
Otherwise we should have thrown a product launch party!

Just an fyi that I'll be taking a bit of a break from coding these holidays.

Will monitor the forums for bugs etc, but no active development for a little while.
If anything I will shift focus to music production and sound design for the new firmware.

**Comment by yatli** [comment]
Now the engineering parts are ready, good luck and have fun with some music!

**Comment by yatli** [comment]
Done, closing.
