### ISSUE TITLE
Update documentation for v2.5

### ISSUE THREAD

**Issue by yatli** [jmamma/MIDICtrl20_MegaCommand#80]

**Comment by jmamma** [comment]
I have to admit, I have not been looking forward to this.

Setup an overleaf account and I will provide you with editor access.

https://www.overleaf.com/

**Comment by jmamma** [comment]
I modified ./mc_display_mirror.py to take a screenshot when pressing '9'

I've gone through and uploaded a bunch of new screenshots 
https://github.com/jmamma/MCL-Documentation/tree/master/MCL%20Documentation/images/images_pending

**Comment by yatli** [comment]
So cool.

Oh wait we got visual utiming now??

**Comment by jmamma** [comment]
Of course. 💰Premium feature 💰

**Comment by yatli** [comment]
MegaCommand:

`> INSERT COIN <`

**Comment by yatli** [comment]
All right first things first. The doc repo is not compiling on my side.
I got TeXLive 2019 and I use latexmk -xelatex.
Can compile earlier revisions with no problem.

**Comment by jmamma** [comment]
I just fixed two compile errors relating to special characters.

It's easier if you just work from overleaf. (It's synced to github)

https://www.overleaf.com/read/gsdhhxzpbgdx

We should be able to work collaboratively .

Just need your account email so I can give you editor access.

**Comment by yatli** [comment]
Ok cool. Just realized that I do have a overleaf account: `yatao.li@live.com`

**Comment by yatli** [comment]
I'm in 🙌

**Comment by jmamma** [comment]
Thanks. It's good to have a different pair of 👀 on the documentation.

I'm going to take a look at the HD44780 display code.

**Comment by yatli** [comment]
May be useful:
https://www.tablesgenerator.com/

**Comment by yatli** [comment]
Half way there.
Renamed all pending images, and moving them out of pending on-demand.

**Comment by yatli** [comment]
@jmamma some screenshots are still missing.

**Comment by yatli** [comment]
Seq group ok.

**Comment by jmamma** [comment]
@yatli which pages are missing?

The serial transfer code is currently located in GUI.display().

Any draw routines that bypass that code can't be captured currently.

**Comment by yatli** [comment]
PTC-A4
PARAM-Edit
RLCK
Ext-Seq

**Comment by jmamma** [comment]
I thought PARAM-Edit was there?
![mcl_screenshot31](https://user-images.githubusercontent.com/8424097/69693809-c767f900-112a-11ea-9a64-80a594694e48.png)

The others are missing.

**Comment by yatli** [comment]
hah, I put it in the overview "Parameter Locks" -- no locks and no trigs registered, so doesn't match the text in the detailed section

**Comment by yatli** [comment]
@jmamma can you do the ram page doc. You will describe it better I'm sure :)

**Comment by jmamma** [comment]
sure

**Comment by yatli** [comment]
I'll add a section about the workflow, and describe the difference between the GRID, the INTERNAL SEQUENCER and the MD SEQUENCER.

**Comment by yatli** [comment]
Done, see "key concepts"

**Comment by yatli** [comment]
Requesting to put my name in there :p

**Comment by jmamma** [comment]
yes of course 🥇

**Comment by jmamma** [comment]
@yatli 

Maybe we should have a Buttons Assignment chart under the Encoders Assignment for each page.

**Comment by jmamma** [comment]
Also, can you sync your changes to github, incase you havent already.
Top left Menu -> Sync

Thanks.

**Comment by yatli** [comment]
Makes sense.

Combine the two to save some space?

**Comment by yatli** [comment]
Synchronized.

**Comment by yatli** [comment]
Synchronized, now with button assignment table.

**Comment by yatli** [comment]
Two left, the LFO page and the RAM page.

**Comment by yatli** [comment]
Done LFO page skeleton.
