### ISSUE TITLE
Black screen after creating a new project

### ISSUE THREAD

**Issue by yatli** [jmamma/MIDICtrl20_MegaCommand#87]

**Comment by jmamma** [comment]
~Probably just need to remove the else if:~

~51   } else if (proj.project_loaded) {~
 ~52     GUI.setPage(&grid_page);~
 ~53     return true;~
 ~54   }~

Hmm actually no.

**Comment by jmamma** [comment]
```
func_call: bool Project::new_project(const char*)
Creating new project
Attempting to extend project file
extension succeeded, trying to close
Initializing project.. please wait
func_call: bool Project::write_header()
Writing project header
Write header success
func_call: bool MCLSysConfig::write_cfg()
Writing cfg
Write cfg okay
project created
func_call: bool Project::load_project(const char*)
Loading project
/qroject005.mcl
func_call: bool Project::check_project_version()
Check project version
func_call: bool MCLSysConfig::write_cfg()
Writing cfg
Write cfg okay
project loaded, setting page to grid
calling cleanup
Pushing page
```

```
 22 bool NewProjectPage::handleEvent(gui_event_t *event) {
 23   // don't handle any events
 24   again:
 25   if (mcl_gui.wait_for_input(newprj, "New Project:", sizeof(newprj))) {
 26       
 27     char full_path[sizeof(newprj) + 5] = {'\0'};
 28     strcat(full_path, "/");
 29     strcat(full_path, newprj);
 30     strcat(full_path, ".mcl");
 31   
 32     gfx.alert("PLEASE WAIT", "CREATING PROJECT");
 33 
 34     DEBUG_PRINTLN(full_path); 
 35     if (SD.exists(full_path)) {
 36       gfx.alert("ERROR", "PROJECT EXISTS");
 37       goto again;
 38     }
 39 
 40     bool ret = proj.new_project(full_path);
 41     if (ret) {
 42       if (proj.load_project(full_path)) {
 43         grid_page.reload_slot_models = false;
 44         DEBUG_PRINTLN("project loaded, setting page to grid");
 45         GUI.setPage(&grid_page);
 46         return true;
 47       } else {
 48         gfx.alert("ERROR", "SD ERROR");
 49         goto again;
 50       }
 51       return false;
 52     }
 53   } else if (proj.project_loaded) {
 54     GUI.setPage(&grid_page);
 55     return true;
 56   }
 57 }
```

Any ideas? Should be setting page to &grid_page

**Comment by jmamma** [comment]
Ah, think i know what's going on.

**Comment by yatli** [comment]
I'm still doing the toggleLed2() thing 😅

**Comment by jmamma** [comment]
I had 
```
 17   gui_event_t event;
 18   handleEvent(&event);
```
in NewProjectPage::init()

```
455   void pushPage(Page *page) {
456     if (currentPage() == page) {
457       DEBUG_PRINTLN("can't push twice");
458       // can't push the same page twice in a row
459       return;
460     }
461     DEBUG_PRINTLN("Pushing page");
462     page->parent = this;
463     if (!page->isSetup) {
464       page->setup();
465       page->isSetup = true;
466     }
467     page->init();
468     page->redisplayPage();
469     page->show();
470     pageStack.push(page);
471   }
```

**Comment by yatli** [comment]
oh ok I got it.

I just observed it as well. The second time a project is created, it returns to the Grid.

**Comment by jmamma** [comment]
moving 
 17   gui_event_t event;
 18   handleEvent(&event);
to loop()

**Comment by yatli** [comment]
Or just remove it?

**Comment by jmamma** [comment]
needs to be there, because new project page doesnt work on card init otherwise.

**Comment by jmamma** [comment]
i think it was only working in your patch because the button release was triggering the handleEvent

**Comment by yatli** [comment]
aha. event injection. :)

**Comment by jmamma** [comment]
hmm putting in loop doesnt work either.

**Comment by yatli** [comment]
Don't do it in handleEvent() then.

**Comment by jmamma** [comment]
yeah moving the whole thing  to loop now.

**Comment by jmamma** [comment]
have you hacked the MD firmware yet, to run MCL natively?

**Comment by yatli** [comment]
I felt dizzy today when I thought about this!

**Comment by jmamma** [comment]
i think NewProjectPage should be removed, and just be a callback function in Project.cpp

**Comment by jmamma** [comment]
textinputpage is doing all the GUI work here.

**Comment by yatli** [comment]
![image](https://user-images.githubusercontent.com/20684720/69806317-90bedb00-121d-11ea-89fd-c8272045350f.png)

HOW DOES THAT LOOK

**Comment by jmamma** [comment]
what am I looking at 👀

**Comment by yatli** [comment]
An emulator running the machinedrum firmware!

**Comment by jmamma** [comment]
define "running" 😁

**Comment by jmamma** [comment]
find me elvis. then i'll be impressed

**Comment by yatli** [comment]
no I/O board, no DSP, just memory and registers

**Comment by jmamma** [comment]
that's pretty cool. how far does the execution get? The MAME notes say that it relies on responses from the sub-chips to detect that it's running on the correct hardware.

**Comment by yatli** [comment]
oh yeah. Some register tampering is required.

**Comment by jmamma** [comment]
when you get some time, are you able to briefly document how you got this up and running,

**Comment by yatli** [comment]
anytime. I can do it now actually

**Comment by jmamma** [comment]
I wonder how easy it would be to get the MD LCD working.

**Comment by yatli** [comment]
https://github.com/jmamma/MIDICtrl20_MegaCommand/issues/88

**Comment by jmamma** [comment]
5bf1b232c9eca357f6fe94b5501b50f7f4f27399

^ This issue should now be fixed.

**Comment by yatli** [comment]
> I wonder how easy it would be to get the MD LCD working.

The I/O board communicates with the CPU board with UART.

**Comment by jmamma** [comment]
> The I/O board communicates with the CPU board with UART.

So we can install a megacommand between the CPU and IO board and hijack the display.

**Comment by yatli** [comment]
maybe the I/O board just accepts high level drawing commands like, put a encoder here, print a string there, clear the screen etc.

well that's good enough already :)

**Comment by jmamma** [comment]
Is there a microcontroller on the IO board?

**Comment by yatli** [comment]
I'm not sure. Didn't really carefully analyze the internals :p

**Comment by yatli** [comment]
@jmamma loaded the latest firmware, crash on create project

**Comment by jmamma** [comment]
@yatli 

I can't replicate. NewProject creation works fine here. Both on out-of-box startup and from system menu.

Can you check your environment is clean.

**Comment by yatli** [comment]
Sure. Trying a clean build now;

**Comment by yatli** [comment]
Still crash. Checking SD card status

**Comment by jmamma** [comment]
What's the symptom of the crash? firmware reboot?

Can you paste debug output.

**Comment by yatli** [comment]
SD card ok. Hardware ok. I swapped in another MC and SD card and still crash.

**Comment by yatli** [comment]
Trying a debug build

**Comment by yatli** [comment]
```
func_call: void MidiSetup::cfg_ports()
Track sizes:
1742
1382
410
501
4
7
Pushing page
7
4
7
func_call: bool MenuPageBase::enter()
calling callback func
Pushing page
7
7
PLEASE WAIT
CREATING PROJECT
/rroject008.mcl
func_call: bool Project::new_project(const char*)
Creating new project
Attempting to extend project file
extension succeeded, trying to close
Initializing project.. please wait
```

No apparent error here

**Comment by jmamma** [comment]
I just swapped in a new MC and no problems here.

**Comment by yatli** [comment]
On crash led2 turns on (and survives the crash, keep on to the next boot)

**Comment by jmamma** [comment]
Is the MD connected?

**Comment by yatli** [comment]
No.

**Comment by jmamma** [comment]
Can you drop back to an earlier commit and see if it still crashes?

**Comment by yatli** [comment]
Adding debug info to Grid::clear_row: not hit.
Trying an earlier build now;

**Comment by yatli** [comment]
roll back to HEAD^^ c7e56a3ebb4464c7f9e5f7a213264b77675b1b28
project create success + blackscreen

**Comment by yatli** [comment]
https://1drv.ms/u/s!Aql6jSQH9uyZhPpIG4OXO20HkXxYgQ?e=jzdRAH

Can you try the build artifact. I suspect it's a toolchain problem.

**Comment by jmamma** [comment]
Yeah crash on new project when I upload that.

**Comment by jmamma** [comment]
204388
MD5 (main.hex) = c58e2eeae0bde3e2a381c89403c3fb9e

**Comment by yatli** [comment]
I'm on `arduino.exe Version: 0.5.0 Commit: 3be2287`
Upgrading to 0.6 now

**Comment by yatli** [comment]
uh oh still crash after upgrading to `arduino-cli 0.6`, `avr-gcc 7.3`

**Comment by jmamma** [comment]
yeah I dont think it's that. I think it's probably a linking issue.

**Comment by jmamma** [comment]
your binary is larger than mine.

**Comment by yatli** [comment]
yeah. I use the arduino toolchain, could be a different build env.

**Comment by jmamma** [comment]
I can compile using the arduino ide,

ill do that now.

**Comment by jmamma** [comment]
Found the MD808 problem. where tracks would be of different length on merge.
Uploaded a patch.

**Comment by jmamma** [comment]
```
avrdude: Device signature = 0x1e9801 (probably m2560)
avrdude: reading input file "/var/folders/0q/mn27032j7bqch7d_krf2603c0000gn/T/arduino_build_215133/sketch_nov29a.ino.hex"
avrdude: writing flash (204466 bytes):
```

**Comment by jmamma** [comment]
no problems with the arduino ide.

**Comment by yatli** [comment]
crash in `row_header.init()` 🤔

**Comment by jmamma** [comment]
do you want to obj dump compare your binary with mine.

**Comment by jmamma** [comment]
[main.zip](https://github.com/jmamma/MIDICtrl20_MegaCommand/files/3903482/main.zip)

forgot the elf file.

**Comment by yatli** [comment]
after inserting some debug:

```
void GridRowHeader::init() {
  active = false;
  for (uint8_t x = 0; x < GRID_WIDTH; x++) {
    DEBUG_DUMP(x);
    track_type[x] = 0;
    model[x] = 0;
  }
}
```
it creates the project fine 😱

**Comment by jmamma** [comment]
last time we had a problem like this is was the PROGMEM space issue.

**Comment by yatli** [comment]
cue: https://github.com/jmamma/MIDICtrl20_MegaCommand/pull/49#issuecomment-544140277

checked PROGMEM, far from being full (less that 0x5000 now)

here's some processed disassembly of the relevant routines.

[asm_diff.zip](https://github.com/jmamma/MIDICtrl20_MegaCommand/files/3903627/asm_diff.zip)

it shows different register allocation, and slightly different PC dancing.
for example:

```asm
; J
   bb de       	rcall	.-650    	; 0x26892 <_ZN5MCLSd10write_dataEPvjP7FatFile.constprop.431>
   01 c0       	rjmp	.+2      	; 0x26b20 <_ZN4Grid10clear_slotEiib.constprop.422+0xac>
   80 e0       	ldi	r24, 0x00	; 0

; =====================
; Y
   c6 de       	rcall	.-628    	; 0x2a432 <_ZN5MCLSd10write_dataEPvjP7FatFile.constprop.500>
```

**Comment by yatli** [comment]
After carefully looking through the disassembly I see some problematic inlined code that mess with the stack.

problem solved. see https://github.com/jmamma/MIDICtrl20_MegaCommand/commit/8adeb43c37965c78c5a89acffe1d12e20a533382

... I need to take a break now.

**Comment by jmamma** [comment]
Thanks @yatli 

I guess it would be nice to know why our compilations differ. 

Are our stack sizes the same?

**Comment by jmamma** [comment]
8KB on this side.

**Comment by yatli** [comment]
how to check for that?

I can see a build parameter --defsym=__stack=0x8021ff, is that it?

**Comment by yatli** [comment]
the inlined code has something weird that it recalls the counter i from SP+62 while filling the row header, looks too big for the local variables.

**Comment by jmamma** [comment]
Just noticed a typo in my makefile

**Comment by jmamma** [comment]
--defsym=__stack=0x8021ff,--section-start,.data=0x82200
should be
--defsym=__stack=0x8021ff,--section-start,.data=0x802200

**Comment by jmamma** [comment]
--section-start,.data=0x8021ff is the end of the stack.
```
registers          |stack_end                    | heap_start                 |
0x800000          0x8021ff,                          0x802200              0x80FFFF  
```

**Comment by jmamma** [comment]
![memory_layout](https://user-images.githubusercontent.com/8424097/69848409-2a45c580-12ce-11ea-9621-8971d6fa9871.png)

memory addresses above are prefixed with 80 (forgot the reason for this)

**Comment by jmamma** [comment]
uploaded a patch for the address typo, the error was also in platform.txt . Although it has never caused issues on my side.
