### ISSUE TITLE
Seq pages: S2+TI switches tracks, but also lay down notes

### ISSUE THREAD

**Issue by yatli** [jmamma/MIDICtrl20_MegaCommand#89]

**Comment by jmamma** [comment]
I think this only occurs if you release shift2 before releasing the trig.

**Comment by jmamma** [comment]
We'd need to implement a mechanism for ignoring trig interface event(s).

**Comment by yatli** [comment]
Can confirm. Moving to backlog.

**Comment by jmamma** [comment]
29cff384423c41fe58f24a22a75377cc394f596e

Should be fixed now.

Can you confirm @yatli
