### ISSUE TITLE
TextInputPage: charpane doesn't exit

### ISSUE THREAD

**Issue by yatli** [jmamma/MIDICtrl20_MegaCommand#90]

**Comment by jmamma** [comment]
In what scenario?

Can you fix :D .

**Comment by yatli** [comment]
Looking into it. Could be really quick to fix :)

**Comment by yatli** [comment]
![image](https://user-images.githubusercontent.com/20684720/69900763-7c601700-13b2-11ea-9c64-2da7ad1be1e2.png)

`#FAIL`

**Comment by jmamma** [comment]
eek. git blame ?

Probably me 😄

**Comment by yatli** [comment]
Yep, I wasn't using conditional here ;)
btw I never used `git blame` before. Nice feature.
