### ISSUE TITLE
SEQ Merge behaviour not clearly defined.

### ISSUE THREAD

**Issue by jmamma** [jmamma/MIDICtrl20_MegaCommand#92]
SeqMerge does just that, it merges the pattern data from the MD in to the internal sequencer.

I think in the general case you want to just copy the entire track from the MD, and overwrite any internal sequencer data. The current function does not do this, it sums the internal seq + md tracks together.

This is related to the track length bug, where merging would not take the MD.pattern length and instead user the internal sequencer's track length.

@yatli 

Thoughts?

**Comment by yatli** [comment]
perhaps max(mdlen, intlen)?

**Comment by jmamma** [comment]
it's not just the legnth.

Do we clear the internal sequencer data on merge.
Currently if MD pattern = 1111000
and            md_track.seq_data.pattern = 00001111
the resulting pattern will be 11111111

**Comment by jmamma** [comment]
On Save page we should probably have 3 options

1) --
2) MD
3) MERGE

**Comment by yatli** [comment]
Ok then:

```
SOURCE
1. SEQ
2. MD [ no play ]
3. MERGE [ no play ]
```

correct?

**Comment by jmamma** [comment]
that's it

**Comment by jmamma** [comment]
```
312 bool MDTrack::store_track_in_grid(int32_t column, int32_t row, int track, bool storepattern,
313                                   bool merge, bool online) {
```

bool merge needs to be converted to uint8_t.

and then replace if (merge)
with a switch (merge)

**Comment by jmamma** [comment]
https://github.com/jmamma/MIDICtrl20_MegaCommand/pull/93

**Comment by jmamma** [comment]
Hmm this seems a little broken.

**Comment by jmamma** [comment]
I think no constructor for MDTrack is setting arraysize = random();
And merging collect fake locks.

**Comment by jmamma** [comment]
@yatli 

I'm considering removing MERGE and limit save functionality to

MD
and
SEQ.

To avoid confusion.

**Comment by jmamma** [comment]
Woops. continue discussion in PR.

**Comment by jmamma** [comment]
I merged the PR. Parameter locks were broken. That is now fixed.

--

Functionality is implemented now.

Workflow feels unpredictable at times. Even i'm forgetting which save mode i'm in. 
Particularly when MD mode toggles to SEQ when sequencer starts.

I've forgotton that I'm in MD mode, and gone to save and lost my internal sequencer data.

**Comment by jmamma** [comment]
Maybe we move the MD save function outside of the SAVE page.
And forego merge.

**Comment by yatli** [comment]
Is MERGE fixed now?

**Comment by jmamma** [comment]
yes it should be.

**Comment by yatli** [comment]
Great, I think I should test it against the lockup bug again.

**Comment by jmamma** [comment]
Which lockup bug? sample send?

**Comment by yatli** [comment]
The chain-write lockup on some rows (and crazy tempo)
I feel this could be relevant.

**Comment by jmamma** [comment]
It's possible.

**Comment by jmamma** [comment]
Found another bug.

Write page is not writing to the current kit when "writing all tracks [Shift 2]"

**Comment by jmamma** [comment]
Actually, i think it's not re-loading the current kit after write.

**Comment by jmamma** [comment]
305 void MCLActions::send_tracks_to_devices() {
...
386   MD.loadKit(MD.pattern.kit);

eek. This was left over from when we deprecated write mode.
We're not sending the pattern to the MD anymore (so we never fetch it).
The MD.pattern.kit is out of date.

**Comment by jmamma** [comment]
encoder[0]->cur = 1 was being set everytime save page opened.
i've removed this, as it has added to the confusion.

**Comment by jmamma** [comment]
@yatli 
SavePage graphic
SEQ -> GRID

should be 

SND -
          ----> GRID 
SEQ -

?

**Comment by jmamma** [comment]
Another save bug
    SEQ mode, would not copy sequencer data to track object for storage
899547be0e44624c505219e4f7510bae9dd4a85b

Hopefully the last.

**Comment by yatli** [comment]
> @yatli
> SavePage graphic
> SEQ -> GRID
> 
> should be
> 
> SND -
> ----> GRID
> SEQ -
> 
> ?

Ah, yes.

**Comment by yatli** [comment]
I remember I've implemented this?

**Comment by jmamma** [comment]
what do you mean?

**Comment by yatli** [comment]
On the Save page, do you see the (SND+SEQ) -> GRID data flow, or just SEQ->GRID?

**Comment by jmamma** [comment]
just SEQ->GRID

**Comment by jmamma** [comment]
Merge shows MD +SEQ -> GRID

**Comment by yatli** [comment]
hmm. I'll update this. :)

**Comment by jmamma** [comment]
I feel like 2.50 release is very close.

**Comment by jmamma** [comment]
fyi: fixed
f1817aa4d69dbf934d94cd380082e8a8660f5c40

**Comment by yatli** [comment]
Cool!
