### ISSUE TITLE
display_charpane() display glitch on out_of_box expereince.

### ISSUE THREAD

**Issue by jmamma** [jmamma/MIDICtrl20_MegaCommand#95]
When NewProjectPage is launched for fresh installs.
Activating the char-pane, there are few characters on the left side that are distorted.

I'm guessing this is because the display buffer is not cleared and some draw commands are using INVERT.

**Comment by yatli** [comment]
should be good with fe300ed

**Comment by jmamma** [comment]
not fixed. adding clear_display before new_project does not fix.

can leave this til after 2.50 release

**Comment by jmamma** [comment]
this might be due to classic_display mode. investigate.
