### ISSUE TITLE
FileBrowser

### ISSUE THREAD

**Issue by jmamma** [jmamma/MIDICtrl20_MegaCommand#96]
There's a bug in file browser. CD in to a  directory that only has say 1 file. If number of entries is less than MAX_VISIBLE_ROWS the directory shows one extra entry (which is usually a file from the parent directory).

@yatli 

If you have some time.

**Comment by yatli** [comment]
yeah I observed this.

**Comment by jmamma** [comment]
ae3fe13eecddd66066b07e1b82c2ba4bec7730f9
fixed
